name: jenkins build trigger workflow

on:
  workflow_call:
    secrets:
      webhook-url:
        required: true
      jenkins-api-token:
        required: true

jobs:
  docker-image-build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: trigger jenkins job.
      uses: appleboy/jenkins-action@master  
      with:
        url: http://52.79.229.130:8080
        user: "chaeeerish"
        token: ${{ secrets.jenkins-api-token }}
        job: "docker-image-pull"