name: main workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-frontend-docker:
    uses: ./.github/workflows/frontend-docker.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  call-workflow-backend-docker:
    needs: call-workflow-frontend-docker
    uses: ./.github/workflows/backend-docker.yml
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  call-workflow-jenkins-build-trigger:
    needs: [call-workflow-frontend-docker, call-workflow-backend-docker]
    uses: ./.github/workflows/jenkins-build-trigger.yml  
    secrets:
      webhook-url: ${{ secrets.WEBHOOK_URL }}
      jenkins-api-token: ${{ secrets.JENKINS_API_TOKEN }}